// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFCjiwwhj1nThPam744cMDBLldz6RBiuk',
    appId: '1:857412064219:web:6b74d1630a029bb1108dfe',
    messagingSenderId: '857412064219',
    projectId: 'meuflash-90e88',
    authDomain: 'meuflash-90e88.firebaseapp.com',
    storageBucket: 'meuflash-90e88.appspot.com',
    measurementId: 'G-4LR1H1286V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5zhfd7cYXnpphXmnkvGcayfV8jnE2NnU',
    appId: '1:857412064219:android:8e8833dd24f2c0ac108dfe',
    messagingSenderId: '857412064219',
    projectId: 'meuflash-90e88',
    storageBucket: 'meuflash-90e88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMZnXxCVBPBJ-8bbw1qMkzCnLwKBnzta8',
    appId: '1:857412064219:ios:1a1ec77dc76ab7bc108dfe',
    messagingSenderId: '857412064219',
    projectId: 'meuflash-90e88',
    storageBucket: 'meuflash-90e88.appspot.com',
    iosBundleId: 'com.example.meuFlash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMZnXxCVBPBJ-8bbw1qMkzCnLwKBnzta8',
    appId: '1:857412064219:ios:2d965bb06c54230d108dfe',
    messagingSenderId: '857412064219',
    projectId: 'meuflash-90e88',
    storageBucket: 'meuflash-90e88.appspot.com',
    iosBundleId: 'com.example.meuFlash.RunnerTests',
  );
}
